name: drdrakify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  get_it: ^7.7.0
  dartz: ^0.10.1
  cloud_firestore:
  just_audio: ^0.9.37

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/static/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/static/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/PlayfairDisplay-Italic.ttf
          style: italic
        - asset: assets/fonts/static/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic
