// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW2wZ8ItaNsgifkaYOJfFT8rwqo2tWh8s',
    appId: '1:202491255123:web:02a195988dbfcbd70ee9a6',
    messagingSenderId: '202491255123',
    projectId: 'drdrakify',
    authDomain: 'drdrakify.firebaseapp.com',
    storageBucket: 'drdrakify.appspot.com',
    measurementId: 'G-1KQJTF061W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASnYhN6XXi2HrQYdMqSUzd1yUKjhjdUs4',
    appId: '1:202491255123:android:0b0ef5d5586d2f800ee9a6',
    messagingSenderId: '202491255123',
    projectId: 'drdrakify',
    storageBucket: 'drdrakify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv_I4hFGp6SOod_3Oy1kWHY01zXGr6HTM',
    appId: '1:202491255123:ios:aeea0dc9cf7f976c0ee9a6',
    messagingSenderId: '202491255123',
    projectId: 'drdrakify',
    storageBucket: 'drdrakify.appspot.com',
    iosBundleId: 'com.example.drdrakify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv_I4hFGp6SOod_3Oy1kWHY01zXGr6HTM',
    appId: '1:202491255123:ios:aeea0dc9cf7f976c0ee9a6',
    messagingSenderId: '202491255123',
    projectId: 'drdrakify',
    storageBucket: 'drdrakify.appspot.com',
    iosBundleId: 'com.example.drdrakify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW2wZ8ItaNsgifkaYOJfFT8rwqo2tWh8s',
    appId: '1:202491255123:web:aeb3ae88d778d9530ee9a6',
    messagingSenderId: '202491255123',
    projectId: 'drdrakify',
    authDomain: 'drdrakify.firebaseapp.com',
    storageBucket: 'drdrakify.appspot.com',
    measurementId: 'G-81V5N7S5JD',
  );
}
